"""bluesky_publisher.py — Publish approved drafts to @argosops.bsky.social.

Reads the oldest approved draft from memory/drafts/approved/, strips the
auto-grader footer + leading markdown, ensures the post fits Bluesky's 300-
grapheme limit, publishes via atproto, and moves the file to a `published/`
sibling so we never reship.

Rate-limited via a JSON counter file keyed by UTC date. Default cap 8/day
(matches research-dive ceiling on Bluesky). Cap can be overridden via
BILLETKIT_BSKY_DAY_CAP in secrets.env.

Called by heartbeat on idle ticks. Returns one of:
  {"action": "published", "uri": "...", "remaining_today": N}
  {"action": "rate_capped", "today": N, "cap": M}
  {"action": "queue_empty"}
  {"action": "draft_too_long", "path": "...", "chars": N}
  {"action": "error", "error": "..."}
"""
from __future__ import annotations

import datetime
import json
import logging
import os
import pathlib
import re
import sys
from typing import Optional

log = logging.getLogger(__name__)

# Memory layout — symlink-free, lives under ROOT/memory
_THIS_FILE = pathlib.Path(__file__).resolve()
ROOT = _THIS_FILE.parent.parent  # /Users/argos/argos
MEMORY = ROOT / "memory"
DRAFTS = MEMORY / "drafts"
APPROVED = DRAFTS / "approved"
PUBLISHED = DRAFTS / "published"
TOO_LONG = DRAFTS / "too-long"
COUNTER = MEMORY / "bluesky-publish-counter.json"

# Make the openclaw-bluesky skill helpers importable
sys.path.insert(0, str(ROOT / "skills" / "openclaw-bluesky" / "lib"))


def _today_utc() -> str:
    return datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d")


def _load_counter() -> dict:
    if not COUNTER.exists():
        return {"date": _today_utc(), "count": 0}
    try:
        d = json.loads(COUNTER.read_text())
        if d.get("date") != _today_utc():
            return {"date": _today_utc(), "count": 0}
        return d
    except Exception:
        return {"date": _today_utc(), "count": 0}


def _save_counter(d: dict) -> None:
    COUNTER.write_text(json.dumps(d))


def _load_secrets() -> dict:
    p = pathlib.Path.home() / ".openclaw" / "secrets.env"
    if not p.exists():
        return {}
    out = {}
    for line in p.read_text().splitlines():
        line = line.strip()
        if line.startswith("export "):
            line = line[7:]
        if "=" in line:
            k, _, v = line.partition("=")
            out[k] = v.strip().strip('"').strip("'")
    return out


def _clean_draft_body(raw: str) -> str:
    """Strip the proactive-draft preamble, the grader footer, surrounding fences."""
    text = raw
    # Drop auto-grader footer (everything from `---\n_Auto-graded:` onward)
    text = re.split(r"\n---\n_Auto-graded:", text, maxsplit=1)[0]
    # Drop heartbeat's proactive_work() preamble:
    #   # Proactive draft · <task_id>
    #
    #   _Generated by heartbeat using <model>_
    #
    #   ---
    #
    #   <body...>
    text = re.sub(
        r"^#\s*Proactive draft[^\n]*\n+_Generated by heartbeat[^\n]*_\n+---\n+",
        "",
        text,
        flags=re.MULTILINE,
    )
    # If after that there's still a leading H1/H2, drop it (rare but harmless)
    lines = text.splitlines()
    while lines and (lines[0].startswith("#") or not lines[0].strip()):
        lines.pop(0)
    text = "\n".join(lines).strip()
    # Strip surrounding triple-backticks if the model wrapped its output
    text = re.sub(r"^```\w*\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    return text.strip()


# Only drafts whose task_id (the filename suffix before .md) is in this set
# are treated as Bluesky-publishable. Everything else (readme-section, x-bio,
# show-hn-title, clawmart-listing, daily-summary) is for the operator, not
# the bot account.
_PUBLISHABLE_TASK_IDS = {"bluesky-post", "bluesky-reply", "agent-journal"}


_TS_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{6}-(?P<tid>[A-Za-z0-9-]+)\.md$")


def _task_id_from_filename(name: str) -> str:
    """Extract task_id from `YYYY-MM-DDTHHMMSS-<task_id>.md`. Empty string on miss."""
    m = _TS_RE.match(name)
    return m.group("tid") if m else ""


def _is_publishable(path: pathlib.Path) -> bool:
    return _task_id_from_filename(path.name) in _PUBLISHABLE_TASK_IDS


def _grapheme_length(text: str) -> int:
    """Bluesky limits to 300 graphemes. Approximate by character count for ASCII;
    use a conservative undercount for unicode emoji/composed-character cases."""
    # Most billetkit drafts are ASCII-only by voice-grader rules (no emoji),
    # so len(text) is the right answer in 99% of cases.
    return len(text)


def publish_next_draft(dry_run: bool = False) -> dict:
    """Publish the oldest approved draft, rate-limited."""
    secrets = _load_secrets()
    cap = int(secrets.get("BILLETKIT_BSKY_DAY_CAP", "8"))

    counter = _load_counter()
    if counter["count"] >= cap:
        return {"action": "rate_capped", "today": counter["count"], "cap": cap}

    if not APPROVED.exists():
        return {"action": "queue_empty"}

    # Only Bluesky-suitable task_ids — README sections, X bios, Show HN titles,
    # ClawMart listings, and daily summaries are NOT tweets and never auto-ship.
    drafts = sorted(p for p in APPROVED.glob("*.md") if p.is_file() and _is_publishable(p))
    if not drafts:
        return {"action": "queue_empty"}

    path = drafts[0]
    body = _clean_draft_body(path.read_text())
    length = _grapheme_length(body)

    # Bluesky cap is 300 graphemes. Hard-fail anything over 295 to be safe.
    if length > 295 or length < 8:
        TOO_LONG.mkdir(parents=True, exist_ok=True)
        target = TOO_LONG / path.name
        path.rename(target)
        return {"action": "draft_too_long", "path": str(target), "chars": length}

    if dry_run:
        return {
            "action": "would_publish",
            "path": str(path),
            "body": body,
            "chars": length,
            "today": counter["count"],
            "cap": cap,
        }

    handle = secrets.get("ARGOS_V2_BSKY_HANDLE") or secrets.get("BSKY_HANDLE")
    pw = secrets.get("ARGOS_V2_BSKY_APP_PASSWORD") or secrets.get("BSKY_APP_PASSWORD")
    if not (handle and pw):
        return {"action": "error", "error": "missing BSKY_HANDLE / BSKY_APP_PASSWORD"}

    try:
        from atproto import Client
        from self_label import ensure_bot_self_label
    except Exception as e:
        return {"action": "error", "error": f"import: {e}"}

    try:
        client = Client()
        client.login(handle, pw)
        # Idempotent — ensures the bot self-label is set every session
        ensure_bot_self_label(client)
        resp = client.send_post(text=body)
        uri = getattr(resp, "uri", None) or str(resp)
    except Exception as e:
        return {"action": "error", "error": f"post: {type(e).__name__}: {e}"}

    # Success — move file to published/ with the post URI in filename + body
    PUBLISHED.mkdir(parents=True, exist_ok=True)
    target = PUBLISHED / path.name
    body_with_meta = (
        f"# Published · {datetime.datetime.now(datetime.UTC).isoformat()}\n\n"
        f"- uri: {uri}\n- chars: {length}\n\n---\n\n{body}\n"
    )
    target.write_text(body_with_meta)
    try:
        path.unlink()
    except Exception:
        pass

    # Increment counter
    counter["count"] += 1
    _save_counter(counter)

    return {
        "action": "published",
        "uri": uri,
        "chars": length,
        "today": counter["count"],
        "cap": cap,
    }


if __name__ == "__main__":
    import argparse

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="Don't actually post, show what would be sent")
    args = ap.parse_args()
    r = publish_next_draft(dry_run=args.dry_run)
    print(json.dumps(r, indent=2))
